name: endeavor

services:
  postgres:
    container_name: endeavor_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  pgadmin:
    container_name: endeavor_pgadmin4
    image: dpage/pgadmin4:8.5
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin_default_email@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin_default_password
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./postgres/pgadmin4/servers.json:/pgadmin4/servers.json
      - ./postgres/pgadmin4/preferences.json:/pgadmin4/preferences.json
    ports:
      - 5433:80

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/root/redis

volumes:
  postgres_data:
  pgadmin_data:
  redis:
