import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SideBar from '@/app/components/SideBar/SideBar'
import './globals.css'
import { redirect } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  // TODO: redirect('/login')
  return (
    <html lang="en">
      <body className={`${inter.className} flex`}>
        <SideBar />
        <div className="p-3 flex-1 bg-green-200">
          <div className="w-full h-full bg-white p-3">{children}</div>
        </div>
      </body>
    </html>
  )
}
